sudo: false
language: node_js
node_js:
  - '8'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run test
  - npm run report-coverage
  - npm run build